spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.rabbitmq.listener.simple.auto-startup=true
spring.rabbitmq.listener.direct.auto-startup=true
shipment.events.enabled=${SHIPMENT_EVENTS_ENABLED:true}

